server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 2638250647
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 86400
  jackson:
    time-zone: Asia/Shanghai
  data:
    mongodb:
      uri: mongodb://localhost:27017/course

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.coursesystem.model